### ISSUE TITLE
Support setting 'away' state from Vera for UI7

### ISSUE THREAD

**Issue by silfreed** [hugheaves/mios_wifi-thermostat#2]
UI7 has different "house modes" that would correlate well to the away state for the thermostat (and vice-versa).  I would think that setting either the house mode to "away" or "vacation" would trigger "away" mode on the termostat, or setting "away" on the thermostat could trigger "away" for the house (that does sound like added complexity).

There is also a "night" mode for the house that could possibly be auto-triggered by the thermostat.. but I don't know if it might not work for the user changing the house mode to "night" to trigger the thermostat changing since that's handled via scheduling right now.

This might be redundant since UI7 allows setting the temperatures for each of these house modes independently; the main problem is that there is no way to schedule house mode changes right now, so it'd be nice to still take advantage of this from the thermostat.

**Comment by hugheaves** [comment]
That would be a nice feature, but unfortunately, even though the thermostat supports a home/away mode, that setting is not readable / settable through the Wi-Fi API.

**Comment by rpeels** [comment]
Could it be the vacation mode in the API:
Emacs!

At 11:32 13/11/2014 -0800, hugheaves wrote:

**Comment by hugheaves** [comment]
The "program_mode" API (I think that's what you're referring to) call looks like it _should_ return the state, but on all the thermostats I have access to, I get the error response:

`{"error": -1}`

To me, it looks like it's probably a placeholder API for a future product. However, if you get something different back on your thermostat, let me know. (You can just access "http://THERMOSTAT_IP_ADDRESS/tstat/program_mode" from your web browser to get the response.)

**Comment by rpeels** [comment]
I get the same response with my ct80. Since the radiothermostat website allows to change the thermostat to an away mode I was hoping this program_mode would do this.

**Comment by hugheaves** [comment]
That is interesting. I'd forgotten that the website allowed you to access that function. (I haven't used the website in ages). So, it sounds like a feature that's exposed through the undocumented "cloud API", but for some unknown reason, doesn't work with their public API. It's a shame radio thermostat no longer has a support forum where this question could be asked as it seems like something that would be nice to see in a future firmware update.

Anyway, thanks for your suggestion and good comments on this!
